baseURL = "http://example.org/"
languageCode = "en-us"
title = "CloudBees Customer Success Onboarding"
theme = "hugo-theme-techdoc"

[Params]

    menu_style = "open-menu" # "open-menu" or "slide-menu"
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts"
    ]
